basic:
  exp_name: ppo
  model_save_dir: /Users/zhuzhengbang/Code_Repos/lfo_grid/gail_torch/assets/learned_models
  tb_log_dir: /Users/zhuzhengbang/Code_Repos/lfo_grid/gail_torch/assets/tblogs

env_specs:
  env_name: GridWorld-v0

exp_params:
  state_only: True
  memory_size: 20000
  update_timestep: 256
  num_updates: 100
  num_threads: 1
  actor_lr: 0.0003
  critic_lr: 0.0003

others:
  model_save_freq: 0
